### ISSUE TITLE
App can't run on IOS devices.. 

### ISSUE THREAD

**Issue by NoviSad557** [Ronak99/Skype-Clone#15]
App working without problem on android devices, but  can't  run on IOS devices...

**Comment by ana675** [comment]
flutter.h , emoji_picker...   

![Screenshot 2020-06-03 at 17 58 49](https://user-images.githubusercontent.com/66259777/83659557-fc667400-a5c3-11ea-8afd-b2c67edf3bee.png)

![Screenshot 2020-06-03 at 18 00 15](https://user-images.githubusercontent.com/66259777/83659692-27e95e80-a5c4-11ea-9f61-476a34359cb5.png)

**Comment by takiuddin93** [comment]
@Ronak99 built his app on windows, I so 'flutter create' builds files for windows. I had same issues when I tried a project of mine.

I fixed it by 'flutter create" on mac and than copied 'lib' folder into mac..that fixed my flutter.h issue.

Very silly way to fix, but I think there are better ways..

for emoji_picker, I think you will have to figure it out on your own, sorry(don't own mac devices to test)
https://pub.dev/packages/emoji_picker

**Comment by Ronak99** [comment]
> App working without problem on android devices, but can't run on IOS devices...

Can you post the stack trace or the logs that you see in the console? That'll help a lot.

**Comment by qwerty684** [comment]
@Ronak99  Here are errors.
![Screenshot 2020-06-11 at 21 36 40](https://user-images.githubusercontent.com/53181006/84431838-45ee3900-ac2c-11ea-927b-b59e7bc2eec6.png)
![Screenshot 2020-06-11 at 21 34 22](https://user-images.githubusercontent.com/53181006/84431844-48509300-ac2c-11ea-99db-1b5e06aee68a.png)

**Comment by AjayrajSingh** [comment]
Seems this problem is caused by interrupting cocoapods install. Try:
1. Remove ios/Flutter/Flutter.framework from your project
2. Run "pod install" in ios directory. Flutter.framework should be generated, including Flutter.h file 
3. Run build

If still this problem persists, consider updating us.

**Comment by wtrungvu** [comment]
@AjayrajSingh I try but it still shows the old error, anyone has any solution for this?

**Comment by realnihal** [comment]
some of the packages have specific installation guidelines for Ios, worth having a look.
